### ISSUE TITLE
GitHub Actionsの学習

### ISSUE THREAD

**Issue by mottox2** [mottox2/til#1]

**Comment by mottox2** [comment]
GitHub Actionsをスケジューラーとしても使えそうなことがわかったのでClose

```
name: Scheduler

# https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
on:
  schedule:
    - cron:  '15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          const issue = github.issues.createComment({...context.repo, issue_number: 1, body: 'Hello github actons!'})
```
